// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TodoListService-ManualJwt.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Defines headers for deleteHealthcheck operation.
    /// </summary>
    public partial class DeleteHealthcheckHeaders
    {
        /// <summary>
        /// Initializes a new instance of the DeleteHealthcheckHeaders class.
        /// </summary>
        public DeleteHealthcheckHeaders() { }

        /// <summary>
        /// Initializes a new instance of the DeleteHealthcheckHeaders class.
        /// </summary>
        public DeleteHealthcheckHeaders(string filter = default(string))
        {
            Filter = filter;
        }

        /// <summary>
        /// filter
        /// </summary>
        [JsonProperty(PropertyName = "filter")]
        public string Filter { get; set; }

    }
}
