// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TodoListService-ManualJwt.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Defines headers for getHealthcheckDetails operation.
    /// </summary>
    public partial class GetHealthcheckDetailsHeaders
    {
        /// <summary>
        /// Initializes a new instance of the GetHealthcheckDetailsHeaders
        /// class.
        /// </summary>
        public GetHealthcheckDetailsHeaders() { }

        /// <summary>
        /// Initializes a new instance of the GetHealthcheckDetailsHeaders
        /// class.
        /// </summary>
        public GetHealthcheckDetailsHeaders(string filter = default(string))
        {
            Filter = filter;
        }

        /// <summary>
        /// filter
        /// </summary>
        [JsonProperty(PropertyName = "filter")]
        public string Filter { get; set; }

    }
}
