// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TodoListService-ManualJwt.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Output
    /// </summary>
    public partial class Output
    {
        /// <summary>
        /// Initializes a new instance of the Output class.
        /// </summary>
        public Output() { }

        /// <summary>
        /// Initializes a new instance of the Output class.
        /// </summary>
        public Output(double? c = default(double?))
        {
            C = c;
        }

        /// <summary>
        /// c
        /// </summary>
        [JsonProperty(PropertyName = "c")]
        public double? C { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.C > 1)
            {
                throw new ValidationException(ValidationRules.InclusiveMaximum, "C", 1);
            }
            if (this.C < 0)
            {
                throw new ValidationException(ValidationRules.InclusiveMinimum, "C", 0);
            }
        }
    }
}
